# Generated by Django 5.2.12 on 2026-04-15 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0002_initial'),
        ('posts', '0005_post_bookmark_postfollow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcollection',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_collections', to='posts.post'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['team', '-created_at'], name='idx_coll_team_created'),
        ),
        migrations.AddConstraint(
            model_name='postcollection',
            constraint=models.UniqueConstraint(fields=('post', 'collection'), name='uniq_post_collection_pair'),
        ),
        migrations.AddConstraint(
            model_name='postcollection',
            constraint=models.UniqueConstraint(fields=('collection', 'sequence_number'), name='uniq_collection_sequence'),
        ),
    ]
