# Generated by Django 5.2.12 on 2026-04-15 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url_endpoint', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='TeamUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('reputation', models.IntegerField(default=1)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('about', models.TextField(blank=True, default='')),
                ('impact', models.BigIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_users', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_users', to='users.user')),
            ],
            options={
                'db_table': 'team_users',
                'constraints': [models.UniqueConstraint(fields=('team', 'user'), name='uniq_team_user')],
            },
        ),
    ]
