# Generated by Django 5.2.12 on 2026-04-15 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0002_initial'),
        ('posts', '0004_postversion'),
        ('teams', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('bookmarks_count', models.IntegerField(default=0)),
                ('closed_reason', models.TextField(blank=True, default='')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('answer_count', models.IntegerField(blank=True, default=None, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('bounty_amount', models.IntegerField(default=0)),
                ('approved_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_for_posts', to='posts.post')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_posts', to='users.user')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_posts', to='posts.post')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.user')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='collections.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='users.user')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='posts.post')),
            ],
            options={
                'db_table': 'bookmarks',
            },
        ),
        migrations.CreateModel(
            name='PostFollow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_follows', to='users.user')),
            ],
            options={
                'db_table': 'post_follows',
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['team', 'type', 'created_at'], name='pst_team_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['team', 'type', 'delete_flag', 'created_at'], name='pst_team_type_del_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['team', 'user', 'created_at'], name='posts_team_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['parent', 'type', 'delete_flag', 'created_at'], name='pst_parent_typ_del_created_ix'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='uniq_bookmark_user_post'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'collection'), name='uniq_bookmark_user_collection'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('post__isnull', False), ('collection__isnull', True)), models.Q(('post__isnull', True), ('collection__isnull', False)), _connector='OR'), name='bookmark_target_exactly_one'),
        ),
        migrations.AddIndex(
            model_name='postfollow',
            index=models.Index(fields=['user', 'created_at'], name='post_follows_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='postfollow',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='uniq_post_follow_user'),
        ),
    ]
