POST_TYPE_QUESTION = 0
POST_TYPE_ANSWER = 1
POST_TYPE_ANNOUNCEMENT = 20
POST_TYPE_HOW_TO_GUIDE = 21
POST_TYPE_KNOWLEDGE_ARTICLE = 22
POST_TYPE_POLICY = 23

ARTICLE_TYPE_VALUES = (
    POST_TYPE_ANNOUNCEMENT,
    POST_TYPE_HOW_TO_GUIDE,
    POST_TYPE_KNOWLEDGE_ARTICLE,
    POST_TYPE_POLICY,
)

COLLECTION_ELIGIBLE_POST_TYPE_VALUES = (POST_TYPE_QUESTION, *ARTICLE_TYPE_VALUES)

POST_TYPE_TO_LABEL = {
    POST_TYPE_QUESTION: 'Question',
    POST_TYPE_ANSWER: 'Answer',
    POST_TYPE_ANNOUNCEMENT: 'Announcement',
    POST_TYPE_HOW_TO_GUIDE: 'How-to Guide',
    POST_TYPE_KNOWLEDGE_ARTICLE: 'Knowledge Article',
    POST_TYPE_POLICY: 'Policy',
}

ARTICLE_TYPE_TO_LABEL = {
    POST_TYPE_ANNOUNCEMENT: POST_TYPE_TO_LABEL[POST_TYPE_ANNOUNCEMENT],
    POST_TYPE_HOW_TO_GUIDE: POST_TYPE_TO_LABEL[POST_TYPE_HOW_TO_GUIDE],
    POST_TYPE_KNOWLEDGE_ARTICLE: POST_TYPE_TO_LABEL[POST_TYPE_KNOWLEDGE_ARTICLE],
    POST_TYPE_POLICY: POST_TYPE_TO_LABEL[POST_TYPE_POLICY],
}

POST_TYPE_TO_KEY = {
    POST_TYPE_QUESTION: 'question',
    POST_TYPE_ANSWER: 'answer',
    POST_TYPE_ANNOUNCEMENT: 'article',
    POST_TYPE_HOW_TO_GUIDE: 'article',
    POST_TYPE_KNOWLEDGE_ARTICLE: 'article',
    POST_TYPE_POLICY: 'article',
}

MIN_TAGS_PER_POST = 1
MAX_TAGS_PER_POST = 5

DEFAULT_ARTICLE_LIST_PAGE_SIZE = 50
MAX_ARTICLE_LIST_PAGE_SIZE = 200
DEFAULT_BOOKMARK_LIST_PAGE_SIZE = 50
MAX_BOOKMARK_LIST_PAGE_SIZE = 200
DEFAULT_FOLLOWED_POSTS_PAGE_SIZE = 50
MAX_FOLLOWED_POSTS_PAGE_SIZE = 200

SEARCH_QUESTION_LIMIT = 12
GLOBAL_SEARCH_PER_TYPE_LIMIT = 10
GLOBAL_SEARCH_TOTAL_LIMIT = 20
COLLECTION_POST_SEARCH_LIMIT = 20

BOUNTY_REASON_OPTIONS = (
    'Authoritative reference needed',
    'Canonical answer required',
    'Current answers are outdated',
    'Draw attention',
    'Improve details',
    'Reward existing answer',
)

BOUNTY_DURATION_DAYS = 7
BOUNTY_MIN_REPUTATION_BUFFER = 1