from django.urls import path
from .views import (
    create_question,
    create_article,
    create_answer,
    update_answer,
    delete_answer,
    undelete_answer,
    approve_answer,
    list_questions,
    search_questions,
    search_global_titles,
    list_articles,
    article_detail,
    question_detail,
    follow_question,
    unfollow_question,
    add_question_mentions,
    remove_question_mention,
    offer_question_bounty,
    award_question_bounty,
    close_question,
    reopen_question,
    delete_question,
    undelete_question,
    add_bookmark,
    remove_bookmark,
    list_bookmarks,
    list_followed_posts,
)

urlpatterns = [
    path('questions/', create_question, name='create-question'),
    path('articles/', create_article, name='create-article'),
    path('questions/<int:question_id>/answers/', create_answer, name='create-answer'),
    path('answers/<int:answer_id>/', update_answer, name='update-answer'),
    path('answers/<int:answer_id>/delete/', delete_answer, name='delete-answer'),
    path('answers/<int:answer_id>/undelete/', undelete_answer, name='undelete-answer'),
    path('questions/<int:question_id>/approve-answer/', approve_answer, name='approve-answer'),
    path('questions/list/', list_questions, name='list-questions'),
    path('questions/search/', search_questions, name='search-questions'),
    path('search/global/', search_global_titles, name='search-global-titles'),
    path('articles/list/', list_articles, name='list-articles'),
    path('articles/<int:article_id>/', article_detail, name='article-detail'),
    path('questions/<int:question_id>/', question_detail, name='question-detail'),
    path('questions/<int:question_id>/follow/', follow_question, name='follow-question'),
    path('questions/<int:question_id>/unfollow/', unfollow_question, name='unfollow-question'),
    path('questions/<int:question_id>/mentions/', add_question_mentions, name='add-question-mentions'),
    path('questions/<int:question_id>/mentions/remove/', remove_question_mention, name='remove-question-mention'),
    path('questions/<int:question_id>/bounty/offer/', offer_question_bounty, name='offer-question-bounty'),
    path('questions/<int:question_id>/bounty/award/', award_question_bounty, name='award-question-bounty'),
    path('questions/<int:question_id>/close/', close_question, name='close-question'),
    path('questions/<int:question_id>/reopen/', reopen_question, name='reopen-question'),
    path('questions/<int:question_id>/delete/', delete_question, name='delete-question'),
    path('questions/<int:question_id>/undelete/', undelete_question, name='undelete-question'),
    path('bookmarks/', add_bookmark, name='add-bookmark'),
    path('bookmarks/remove/', remove_bookmark, name='remove-bookmark'),
    path('bookmarks/list/', list_bookmarks, name='list-bookmarks'),
    path('follows/list/', list_followed_posts, name='list-followed-posts'),
]
