# Centralized reputation and bounty tuning values.
# Update values here to propagate changes across all call sites.

MIN_REPUTATION = 1

# Vote reputation deltas (applied by votes app).
UPVOTE_RECEIVER_GAIN = 10
UPVOTE_RECEIVER_LOSS = -10

DOWNVOTE_RECEIVER_LOSS = -2
DOWNVOTE_RECEIVER_REFUND = 2

DOWNVOTE_VOTER_COST = -1
DOWNVOTE_VOTER_REFUND = 1

# Accept/unaccept answer deltas (applied by posts app).
ANSWER_ACCEPT_GAIN = 15
ANSWER_UNACCEPT_LOSS = -15

# Bounty amount and related reputation thresholds.
BOUNTY_AMOUNT = 50

# Reputation history reason keys.
REPUTATION_REASON_UPVOTE = 'upvote'
REPUTATION_REASON_UNUPVOTE = 'unupvote'
REPUTATION_REASON_DOWNVOTE = 'downvote'
REPUTATION_REASON_UNDOWNVOTE = 'undownvote'
REPUTATION_REASON_DOWNVOTED = 'downvoted'
REPUTATION_REASON_UNDOWNVOTED = 'undownvoted'
REPUTATION_REASON_ACCEPT = 'accept'
REPUTATION_REASON_UNACCEPT = 'unaccept'
REPUTATION_REASON_BOUNTY_OFFERED = 'bounty offered'
REPUTATION_REASON_BOUNTY_EARNED = 'bounty earned'

REPUTATION_REASON_VALUES = (
	REPUTATION_REASON_UPVOTE,
	REPUTATION_REASON_UNUPVOTE,
	REPUTATION_REASON_DOWNVOTE,
	REPUTATION_REASON_UNDOWNVOTE,
	REPUTATION_REASON_ACCEPT,
	REPUTATION_REASON_UNACCEPT,
	REPUTATION_REASON_DOWNVOTED,
	REPUTATION_REASON_UNDOWNVOTED,
	REPUTATION_REASON_BOUNTY_OFFERED,
	REPUTATION_REASON_BOUNTY_EARNED,
)
